#!/bin/bash

IFS=$'\n'
BROWSER="/usr/bin/firefox" # Open bookmark with browser of your choice

PLACES_PATH_CACHE="$HOME/.cache/firefox-places-path"
BOOKMARKS_PATH="$HOME/.cache/places.sqlite"

# Cache the location of the places database
if [ ! -f "$PLACES_PATH_CACHE" ]
then
    path=$(find "$HOME/.mozilla/firefox/" | grep "places.sqlite$")
    echo $path > "$HOME/.cache/firefox-places-path"
    
    cp $path $BOOKMARKS_PATH
fi

DB_PATH="$(cat ${PLACES_PATH_CACHE})"

# Firefox locks places DB when browser is running
if [ -n "$(cmp $DB_PATH $BOOKMARKS_PATH)" ]
then
    cp $DB_PATH $BOOKMARKS_PATH
fi

tqry=$(sqlite3 ${BOOKMARKS_PATH} "SELECT title FROM moz_bookmarks WHERE NOT fk=''")

read -d '' -ra tarray <<< "$tqry"

choice=$(printf "%s\n" "${tarray[@]}" | rofi -dmenu -i)

bookmark_id=$(sqlite3 ${BOOKMARKS_PATH} "SELECT fk FROM moz_bookmarks WHERE title=\"${choice}\"")

url=$(sqlite3 ${BOOKMARKS_PATH} "SELECT url FROM moz_places WHERE id=${bookmark_id}")

if [ -n "$url" ]
then
    $BROWSER $url
fi
